project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
github_token_env: GITHUB_TOKEN

"files": [
  {
    "source": "/_sources/*.pot",
    "translation": "/LC_MESSAGES/%two_letters_code%_%file_name%.po",
    "translation_replace": {
      "ja_": ""
    },
  }
]
